#!/bin/bash
# Regenerate Sources/tokiwatari/GeneratedSkills.swift from skills/tokiwatari/**.
# The binary must be self-contained (no bundle directory next to it), so the
# skill files distributed by `tokiwatari install-skill` are embedded as base64.
set -euo pipefail
cd "$(dirname "$0")/.."
out=Sources/tokiwatari/GeneratedSkills.swift

{
  echo "// Generated by scripts/embed-skills.sh from skills/tokiwatari/ — do not edit."
  echo "// Regenerate with: scripts/embed-skills.sh"
  echo ""
  echo "enum BundledSkills {"
  echo "    static let files: [(path: String, base64Contents: String)] = ["
  (
    cd skills/tokiwatari
    find . -type f | sed 's|^\./||' | LC_ALL=C sort | while read -r file; do
      base64_contents=$(base64 -i "$file" | tr -d '\n')
      echo "        (path: \"$file\", base64Contents: \"$base64_contents\"),"
    done
  )
  echo "    ]"
  echo "}"
} > "$out"

echo "wrote $out"
